[build]
  base = ""
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/"
    [headers.values]
      Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
      X-Frame-Options = "DENY"
      X-Content-Type-Options = "nosniff"
      X-XSS-Protection = "1; mode=block"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https:; font-src 'self' https:; object-src 'none'"
